### ISSUE TITLE
关于数据集下载

### ISSUE THREAD

**Issue by bugczw** [shenzaimin/CCKS-2021-Financial-Event-Extraction_Rank-6th#1]
你好，想问一下这个比赛的数据集能分享一下吗？想研究一下因果事件抽取的方法

**Comment by shenzaimin** [comment]
本项目为事件抽取部分，因果关系抽取不在这个项目中，可以在下方获取
链接: https://pan.baidu.com/s/1kjE-gSa4JzxOt_eTwoP5Gg?pwd=u2d0 提取码: u2d0
